version: '2'
services:
  postgres:
    image: postgres:10.5-alpine
    ports:
    - 5432:5432
  app:
    image: nemmo/node-postgres-test:1.0
    build:
      context: .
    working_dir: /app
    command: yarn start
    env_file:
      - .env
    volumes:
    - .:/app
    ports:
    - 8080:8080
